NewGameStore/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NewGameStore.Models
{
    public class Game
    {
        public int GameID { get; set; }

        [StringLength(50)]
        public string Title { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Year { get; set; }

        public string Description { get; set; }
        
        [Required]
        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Value { get; set; }
        
        [ForeignKey("Genre")]
        public int GenreID { get; set; }


        [ForeignKey("Publisher")]
        public int PublisherID { get; set; }

        [ForeignKey("ESRB")]
        public int ESRBID { get; set; }

        public string Details
        {
            get
            {
                return (this.Title + " (" + this.Publisher.Name + ", " + this.Year.Year + ")");

            }
        }

        public virtual ESRB ESRB { get; set; }
        public virtual Publisher Publisher { get; set; }

        public virtual Genre Genre { get; set; }

    }
}

NewGameStore/Models/Genre.cs
using NewGameStore.Models.CustomValidator;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NewGameStore.Models
{
    public class Genre
    {
        public int GenreID{ get; set; }

        [StringLength(30)]
        [Index(IsUnique = true)]
        [Display(Name = "Genre")]
        [GenreValidator]
        public string Name { get; set; }
    }
}

NewGameStore/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewGameStore.DAL;
using NewGameStore.Models;
using System.Globalization;
using NewGameStore.ViewModels;
using NewGameStore.DAL.Repositories;
using System.Data.SqlClient;

namespace NewGameStore.Controllers
{
    public class GamesController : Controller
    {
        private IGameRepository gameRepository;

        public GamesController()
        {
            this.gameRepository = new GameRepository(new StoreContext());
        }

        public GamesController(IGameRepository gameRepository)
        {
            this.gameRepository = gameRepository;
        }
        // GET: Games
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 0);
            var games = gameRepository.GetGames();
            int maxPage = games.Count()/pageSize;

            if (page <= 0) pageNumber = 0;
            if (page >= maxPage) pageNumber = maxPage;
            

            ViewBag.CurrentPage = pageNumber;
            if (!String.IsNullOrEmpty(searchString))
            {
                games = games.Where(s => s.Title.ToUpper().Contains(searchString.ToUpper()));
                
            }
            games = games.OrderBy(g => g.Title);
            
            
            return View(games.Skip(pageSize * (pageNumber)).Take(pageSize).ToList());
        }
        
        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = gameRepository.GetGameByID(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.ESRBID = new SelectList(gameRepository.GetRatings(), "ESRBID", "Rating"); 
            ViewBag.PublisherID = new SelectList(gameRepository.getPublishers(), "PublisherID", "Name");
            ViewBag.GenreID = new SelectList(gameRepository.getGenres(), "GenreID", "Name");

            return View();
        }
        
        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GameID,Title,ESRBID,Year,Description,Value,PublisherID, GenreID")] Game game)
        {
            ViewBag.ESRBID = new SelectList(gameRepository.GetRatings(), "ESRBID", "Rating");
            ViewBag.PublisherID = new SelectList(gameRepository.getPublishers(), "PublisherID", "Name");
            ViewBag.GenreID = new SelectList(gameRepository.getGenres(), "GenreID", "Name");
            if (ModelState.IsValid)
            {    
                gameRepository.InsertGame(game);
                gameRepository.Save();
                
            }
            return RedirectToAction("Index");
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = gameRepository.GetGameByID(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.ESRBID = new SelectList(gameRepository.GetRatings(), "ESRBID", "Rating");
            ViewBag.PublisherID = new SelectList(gameRepository.getPublishers(), "PublisherID", "Name");
            ViewBag.GenreID = new SelectList(gameRepository.getGenres(), "GenreID", "Name");
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GameID,Title,ESRBID,Year,Description,Value,PublisherID, GenreID")] Game game)
        {
            if (ModelState.IsValid)
            {
                gameRepository.UpdateGame(game);
                gameRepository.Save();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = gameRepository.GetGameByID(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            gameRepository.DeleteGame(id);
            gameRepository.Save();

            return RedirectToAction("Index");
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                gameRepository.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

NewGameStore/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewGameStore.DAL;
using NewGameStore.Models;
using NewGameStore.DAL.Repositories;

namespace NewGameStore.Controllers
{
    public class GenresController : Controller
    {
        private IGenreRepository genreRepository;

        public GenresController()
        {
            this.genreRepository = new GenreRepository(new StoreContext());
        }

        // GET: Genres
        public ActionResult Index()
        {
            return View(genreRepository.GetGenres());
        }

        public ActionResult GamesPerGenre(string genre)
        {
            ViewBag.Genre = genre;
            return View();
        }

        // GET: Genres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreID,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {

                genreRepository.InsertGenre(genre);
                genreRepository.Save();
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        //GET: Genres/Games/5
        public ActionResult Games(int id)
        {
            var name = from g in genreRepository.GetGenres()
                            where g.GenreID == id
                            select g.Name;
            ViewBag.Genre = (String)name.First();
            return View(genreRepository.GamesPerGenre(id).OrderBy(g=> g.Title));
        }

       
        // GET: Genres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = genreRepository.GetGenreByID(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            genreRepository.DeleteGenre(id);
            genreRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                genreRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewGameStore/Views/Genres/Create.cshtml
@model NewGameStore.Models.Genre

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewGameStore/Views/Genres/Delete.cshtml
@model NewGameStore.Models.Genre

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

NewGameStore/Views/Genres/Details.cshtml
@model NewGameStore.Models.Genre

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GenreID }, new { @class = "btn btn-default" }) 
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</p>

NewGameStore/Views/Genres/Edit.cshtml
@model NewGameStore.Models.Genre

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GenreID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewGameStore/Views/Genres/Games.cshtml
@model IEnumerable<NewGameStore.Models.Game>

@{ 
    ViewBag.Title = "GamesPerGenre";
}

<h2>@Html.Raw(ViewBag.Genre) Games</h2>
<p>
    @Html.ActionLink("Back to Genres", "Index", null, new { @class = ("btn btn-default")})
</p>
<table class="table">
    <tr>
        <th>
            Title
        </th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>

            <td>
            </td>
        </tr>
    }

</table>

NewGameStore/Views/Genres/Index.cshtml
@model IEnumerable<NewGameStore.Models.Genre>

@{
    ViewBag.Title = "Index";
}

<h2>Genres</h2>

<p>
    @Html.ActionLink("New Genre", "Create", null, new { @class = "btn btn-success" })
    @Html.ActionLink("View Publishers", "../Publishers", null, new { @class = "btn btn-default"})
    @Html.ActionLink("Back to Games", "../Games/Index", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("View Games", "Games", new { id = item.GenreID }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id=item.GenreID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>