NewGameStore/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;


namespace NewGameStore.Models
{
    public class Client
    {
        public Client()
        {
            this.Active = true;
        }

        [Key]
        public int ClientID { get; set; }

        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        public string FirstMidName { get; set; }

        [StringLength(50)]
        [Display(Name ="Last Name")]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        [DefaultValue(true)]
        public bool Active { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return FirstMidName + " " + LastName;
            }
        }

        public int Age
        {
            get
            {
                DateTime today = DateTime.Now;
                int age = (today - this.BirthDate).Days / 365;
                return age;
            }
        }

        public virtual ICollection<Rental> Rentals{ get; set; }

        public virtual ICollection<Fee> Fees { get; set; }
    }
}

NewGameStore/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewGameStore.DAL;
using NewGameStore.Models;
using NewGameStore.DAL.Repositories;

namespace NewGameStore.Controllers
{
    public class ClientsController : Controller
    {
        private IClientRepository clientRepository;

        public ClientsController()
        {
            this.clientRepository = new ClientRepository(new StoreContext());
        }

        public ClientsController(IClientRepository clientRepository)
        {
            this.clientRepository = clientRepository;
        }
            
        // GET: Clients
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 0);
            var clients = clientRepository.GetActiveClients();
            int maxPage = clients.Count() / pageSize;

            if (page <= 0) pageNumber = 0;
            if (page >= maxPage) pageNumber = maxPage;

            ViewBag.CurrentPage = pageNumber;
            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(c => c.FullName.ToUpper().Contains(searchString.ToUpper()));
            }
            clients = clients.OrderBy(c => c.LastName);
            return View(clients.Skip(pageSize * (pageNumber)).Take(pageSize).OrderBy(c=> c.FirstMidName).ToList());
        }

        public ActionResult GamesPerAge(int id)
        {
            Client client = clientRepository.GetClientByID(id);
            ViewBag.Name = client.FullName;
            ViewBag.Age = client.Age;
            IEnumerable<Game> list = clientRepository.AvailableGames(client.Age);
            return View(list.OrderBy(g => g.Title).OrderBy(g=> g.ESRBID));
        }

        public ActionResult Log(string searchString, int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 0);
            var clients = clientRepository.GetInactiveClients();
            int maxPage = clients.Count() / pageSize;

            if (page <= 0) pageNumber = 0;
            if (page >= maxPage) pageNumber = maxPage;

            ViewBag.CurrentPage = pageNumber;
            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(c => c.FullName.ToUpper().Contains(searchString.ToUpper()));
            }
            clients = clients.OrderBy(c => c.LastName);
            return View(clients.Skip(pageSize * (pageNumber)).Take(pageSize).ToList());
        }


        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = clientRepository.GetClientByID(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientID,FirstMidName,LastName,BirthDate")] Client client)
        {
            if (ModelState.IsValid)
            {
                clientRepository.InsertClient(client);
                clientRepository.Save();
                return RedirectToAction("Index");
            }

            return View(client);
        }
        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = clientRepository.GetClientByID(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientID,FirstMidName,LastName,BirthDate")] Client client)
        {
            if (ModelState.IsValid)
            {
                clientRepository.UpdateClient(client);
                clientRepository.Save();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Client client = clientRepository.GetClientByID(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            clientRepository.DeleteClient(id);
            clientRepository.Save();
            return RedirectToAction("Index");
        }

        // GET: Clients/Activate/5
        public ActionResult Activate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Client client = clientRepository.GetClientByID(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Activate/5
        [HttpPost, ActionName("Activate")]
        [ValidateAntiForgeryToken]
        public ActionResult ActivateConfirmed(int id)
        {
            clientRepository.ActivateClient(id);
            clientRepository.Save();
            return RedirectToAction("Log");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                clientRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewGameStore/Views/Clients/Activate.cshtml
@model NewGameStore.Models.Client

@{
    ViewBag.Title = "Activate";
}

<h2>Activate Client</h2>

<h3>Are you sure you want to deactivate this client?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Activate" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Log", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

NewGameStore/Views/Clients/Create.cshtml
@model NewGameStore.Models.Client

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", @id = "BirthDate" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewGameStore/Views/Clients/Delete.cshtml
@model NewGameStore.Models.Client

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

NewGameStore/Views/Clients/Details.cshtml
@model NewGameStore.Models.Client

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClientID }, new { @class = "btn btn-default" })
    @Html.ActionLink("Back to List", "Index", null,  new { @class = "btn btn-default" })
</p>

NewGameStore/Views/Clients/Edit.cshtml
@model NewGameStore.Models.Client

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", @id = "BirthDate" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewGameStore/Views/Clients/GamesPerAge.cshtml
@model IEnumerable<NewGameStore.Models.Game>

@{ 
    ViewBag.Title = "AppropriateGames";
}

<h2>Suitable games for @Html.Raw(ViewBag.Name) (Age: @Html.Raw(ViewBag.Age))</h2>
<p>
    @Html.ActionLink("Back to Clients", "Index", null, new { @class = ("btn btn-default")})
</p>
<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Rating
        </th>
        <th>
            Suitable age
        </th>
        <th></th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ESRB.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ESRB.Age)
            </td>
            <td>
                @Html.ActionLink("Details", "../Games/Details/", new { id = item.GameID}, new {@class = ("btn btn-default")})
            </td>
        </tr>
    }

</table>

NewGameStore/Views/Clients/Index.cshtml
@model IEnumerable<NewGameStore.Models.Client>

@{
    ViewBag.Title = "Index";
}

<h2>Clients</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new {@class = "btn btn-success" })
    @Html.ActionLink("Inactive Clients", "Log", null, new { @class = "btn btn-default"})
</p>
@using (Html.BeginForm("Index", "Clients", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-info"/>
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstMidName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem=> item.Age)
        </td>
        <td>
            @Html.ActionLink("Suitable Games", "GamesPerAge", new { id=item.ClientID}, new { @class = "btn btn-default"})
            @Html.ActionLink("Edit", "Edit", new { id=item.ClientID }, new { @class = "btn btn-default" }) 
            @Html.ActionLink("Deactivate", "Delete", new { id=item.ClientID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>
<td>
    @Html.ActionLink("Previous Page", "", new { page = ViewBag.CurrentPage - 1 }) |
    @Html.ActionLink("Next Page", "", new { page = ViewBag.CurrentPage + 1 })
</td>

NewGameStore/Views/Clients/Log.cshtml
@model IEnumerable<NewGameStore.Models.Client>

@{
    ViewBag.Title = "Index";
}

<h2>Clients</h2>
<p>
    @Html.ActionLink("Active Clients", "Index", null, new { @class = "btn btn-default" })
</p>
@using (Html.BeginForm("Index", "Clients", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-info" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstMidName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ClientID }, new { @class = "btn btn-default" })
                @Html.ActionLink("Activate", "Activate", new { id = item.ClientID }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }

</table>
<td>
    @Html.ActionLink("Previous Page", "", new { page = ViewBag.CurrentPage - 1 }) |
    @Html.ActionLink("Next Page", "", new { page = ViewBag.CurrentPage + 1 })
</td>